# Generated by Django 5.1.4 on 2025-01-04 00:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioEscolar',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Horário Escolar',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Turma',
            },
        ),
    ]
